language: ruby
rvm:
  - 2.1.0
before_script:
  - mysql -e 'create database myproject_test;'
notifications:
  hipchat: '<TOKEN>@<ROOM NAME>'

# CI時に submodule を無視
git:
  submodules: false 

# bundle install をキャッシュ
# see: http://bekkou68.hatenablog.com/entry/2014/04/02/210754
cache: bundler
